global_asm!(
    ".global io_out32",
    "io_out32:",
    "    mov dx, di",
    "    mov eax, esi",
    "    out dx, eax",
    "    ret",
    "",
    ".global io_in32",
    "io_in32:",
    "    mov dx, di",
    "    in eax, dx",
    "    ret",
    "",
    ".global get_cs",
    "get_cs:",
    "    xor eax, eax",
    "    mov ax, cs",
    "    ret",
    "",
    ".global load_idt",
    "load_idt:",
    "    push rbp",
    "    mov rbp, rsp",
    "    sub rsp, 10",
    "    mov [rsp], di",
    "    mov [rsp + 2], rsi",
    "    lidt [rsp]",
    "    mov rsp, rbp",
    "    pop rbp",
    "    ret",
);
